### ISSUE TITLE
Test Postprocessing, XSLT Converter, User

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-docker#27]
Please test these three modules on `http://rv2622.1blu.de:4000`. E.g. 

```
curl -X GET -H "Cache-Control: no-cache" -H "Postman-Token: 79bbd86b-d9e5-2434-8c12-a8045d4c879e" "http://rv2622.1blu.de:4000/toolbox/convert/manage"
```

**Comment by bgrusdt** [comment]
The call to 

```
http://{{baseUrl}}/toolbox/convert/documents/extract-entities-only?informat=turtle&outformat=csv
```

in **filter / POST documents** only works on all three, dev/live/docker, when Content-Type=text/turtle and Accept=text/comma-separated-values headers are used instead of informat and outformat parameters.

It results in this Error-Message:

```
{
  "exception": "eu.freme.common.exception.FREMEHttpException",
  "path": "/toolbox/convert/documents/extract-entities-only",
  "message": "The content-type header 'text/plain' is not one of the supported supported RDF serialization formats.",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1476958053023
}
```

**Comment by bgrusdt** [comment]
@jnehring This is all I found, the rest worked. Was this the call that didn't work for you?

**Comment by jnehring** [comment]
Thank you for testing. It is ok that the SPARQL converter endpoint do not accept informat or outformat parameters, the [api documentation](https://freme-project.github.io/api-doc/full.html#!/Toolbox%2FPostprocessing-Filter/post_toolbox_convert_documents_name) says that these endpoints use content-type and accept headers only.

Of the 5 XSLT converters I have in the collection, 3 did not work:
- identity transformation
- html-to-xliff20
- xslt-with-param

**Comment by jnehring** [comment]
I updated the configuration of the broker and added the e-internationalization blacklist parameters from the dev and live broker. This solved the problems with identity transformation and xslt-with-param. The Problem with html-to-xliff20 still exists. We need to fix this problem later.

The curl request for the problem with html-to-xliff20 is

```
curl -X POST -H "Content-Type: text/xml" -H "Accept: text/xml" -H "Cache-Control: no-cache" -H "Postman-Token: 06c1e8bf-32be-793f-c220-2a4441858d70" -d '<html>
    <head>
        <title>@@@</title>
        <script type="application/xml" id="orgdoc">
            <xliff xmlns="urn:oasis:names:tc:xliff:document:2.0"
                version="2.0"
                srcLang="en"
                trgLang="fr">
                <file id="f1">
                    <unit id="u1">
                        <segment>
                            <anchor xmlns="http://www.w3.org/1999/xhtml" id="n1"/>
                        </segment>
                    </unit>
                </file>
            </xliff>
        </script>
    </head>
    <body>
        <div id="xyz1xyz">
            <p id="n1">We very much welcome you in the city of <span
                    data-its-ta-class-refs="http://dbpedia.org/ontology/City http://dbpedia.org/ontology/Location http://dbpedia.org/ontology/PopulatedPlace http://nerd.eurecom.fr/ontology#Location http://dbpedia.org/ontology/Place http://dbpedia.org/ontology/Settlement"
                    its-ta-class-ref="http://dbpedia.org/ontology/City"
                    its-ta-confidence="0.9990764748481397"
                    its-ta-ident-ref="http://dbpedia.org/resource/Prague">Prague</span>, home of
                XML!</p>
        </div>
    </body>
</html>' "http://rv2622.1blu.de:4000/toolbox/xslt-converter/documents/html-to-xliff20"
```

http response

```
{
  "exception": "eu.freme.common.exception.FREMEHttpException",
  "path": "/toolbox/xslt-converter/documents/html-to-xliff20",
  "message": "First argument to parse-xml() is not a well-formed and namespace-well-formed XML document. XML parser reported: Error reported by XML parser processing : Premature end of file.",
  "error": "Internal Server Error",
  "status": 500,
  "timestamp": 1477557473445
}
```

the log message

```
eu.freme.common.exception.FREMEHttpException: First argument to parse-xml() is not a well-formed and namespace-well-formed XML document. XML parser reported: Error reported by XML parser processing : Premature end of file.
        at eu.freme.bservices.controllers.xsltconverter.XsltConverterController.filter(XsltConverterController.java:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by jnehring** [comment]
The docker installation contained another XSLT template then the freme-live installation. I updated in the docker container and it works.
