### ISSUE TITLE
Solr starts as user "solr"

### ISSUE THREAD

**Issue by ghsnd** [freme-project/freme-docker#36]
The solr container `freme-solr` runs a process as user `solr`. This gives errors like 

```
freme-solr_1      | 6578 ERROR (coreLoadExecutor-6-thread-1) [   x:elinker] o.a.s.c.CoreContainer Error creating core [elinker]: /opt/solr/server/solr/elinker/data/index/write.lock
freme-solr_1      | org.apache.solr.common.SolrException: /opt/solr/server/solr/elinker/data/index/write.lock
freme-solr_1      | 	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:820)
freme-solr_1      | 	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:658)
freme-solr_1      | 	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:820)
freme-solr_1      | 	at org.apache.solr.core.CoreContainer.access$000(CoreContainer.java:90)
freme-solr_1      | 	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:473)
freme-solr_1      | 	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:464)
freme-solr_1      | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
freme-solr_1      | 	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor$1.run(ExecutorUtil.java:231)
freme-solr_1      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
freme-solr_1      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
freme-solr_1      | 	at java.lang.Thread.run(Thread.java:745)
freme-solr_1      | Caused by: java.nio.file.AccessDeniedException: /opt/solr/server/solr/elinker/data/index/write.lock
freme-solr_1      | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
freme-solr_1      | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
freme-solr_1      | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
freme-solr_1      | 	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
freme-solr_1      | 	at java.nio.channels.FileChannel.open(FileChannel.java:287)
freme-solr_1      | 	at java.nio.channels.FileChannel.open(FileChannel.java:335)
freme-solr_1      | 	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:113)
freme-solr_1      | 	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
freme-solr_1      | 	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
freme-solr_1      | 	at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:94)
freme-solr_1      | 	at org.apache.lucene.index.IndexWriter.isLocked(IndexWriter.java:4487)
freme-solr_1      | 	at org.apache.solr.core.SolrCore.initIndex(SolrCore.java:522)
freme-solr_1      | 	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:761)
freme-solr_1      | 	... 10 more
```

The problem is dat the directory `/opt/freme-data/solr` is not created as user `solr`. Recursively chowning the directory to `solr` is a workaround, but this should be fixed another way.

I don't know how critical this is...

**Comment by jnehring** [comment]
I could reproduce the problem and could also use the workaround using chown.

What is the issue with the work around? We could add the chown command to the docker installation instructions.

**Comment by ghsnd** [comment]
> What is the issue with the work around? We could add the chown command to the docker installation instructions.

It depends if the one installing FREME is willing or allowed to add a user `solr` to the system. Anyway, it is a good idea to document it in the instructions.

**Comment by jnehring** [comment]
I added the chmod command to [use freme on docker guide](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/use-freme-docker.html).

**Comment by jnehring** [comment]
this is solved by the updated documentation
